### ISSUE TITLE
string replace bug in substitutePaths?

### ISSUE THREAD

**Issue by barne856** [USACE/cc-java-sdk-depricated#4]
https://github.com/USACE/cc-java-sdk/blob/6efea2ed51ccfc6207c0c441d66a0d81c6914847/src/main/java/usace/cc/plugin/PluginManager.java#L82

This code replaces the first substring matching `"\\{" + result + "\\}"` but the regex would find anything between the curly braces (i.e. for the string `"/some/path/{ENV::VAR}"` result = `"ENV::VAR"`. So the replacement will never occur since it is looking for `\{ENV::VAR\}` which does not exist in the path.

Maybe I'm missing something, but shouldn't this be the correct way:

```Java
path = path.replaceFirst("{"+result+"}", val);
```

**Comment by HenryGeorgist** [comment]
the replaceFirst method expects a regex expression as a string so i have to dynamically create a regex. the backslash is there for regex and the second backslash was for the escape of the backslash.

**Comment by barne856** [comment]
Gotcha, marking as closed.
